name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: tests
      run: |
        echo $GITHUB_WORKFLOW
        echo $GITHUB_REF
        echo ${GITHUB_REF##/*}
        echo ${GITHUB_REF%%/*}
